name: Display Name Script

on:
  push:
    branches:
      - main

jobs:
  display_name:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Docker Container
      run: |
        docker run -d --name my_container my_image
        docker exec my_container bash -c 'echo "Your First Name: YourFirstName"'
        docker exec my_container bash -c 'echo "Your Last Name: YourLastName"'
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
